/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI.spia;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Messaggio;

/**
 *
 * @author user
 */
public class ListaMessaggiCifrati extends javax.swing.JFrame {

    public static Messaggio getMessaggio() {
        final SynchronizedBuffer<Messaggio> buff = new SynchronizedBuffer<>();

        new Thread( new Runnable() {
            public void run() {
                ListaMessaggiCifrati listaMessaggiCifrati = new ListaMessaggiCifrati(buff);
                listaMessaggiCifrati.setVisible(true);
            }
        } ).start();
        
        return buff.get();
    }
    public static class SynchronizedBuffer<T> {
        private T contents;
        private boolean available = false;

        public synchronized T get() {
            while (available == false) {
                try {
                    wait();
                } catch (InterruptedException e) { }
            }
            available = false;
            notifyAll();
            return contents;
        }

        public synchronized void put(T value) {
            while (available == true) {
                try {
                    wait();
                } catch (InterruptedException e) { }
            }
            contents = value;
            available = true;
            notifyAll();
        }
    }
    
    SynchronizedBuffer<Messaggio> syncBuffer;
    public ListaMessaggiCifrati( SynchronizedBuffer<Messaggio> c ) {
        this();
        this.syncBuffer = c;
    }
    /**
     * Creates new form NuovaSessione
     */
    public ListaMessaggiCifrati () {
        initComponents();
        List<Messaggio> list = Messaggio.getMessaggi();
        Messaggio[] arr = list.toArray( new Messaggio[list.size()] );
        for( Messaggio m: arr) {
            m.setToStringF("%lingua%, %testoCif%");
        }
        jList1.setListData(arr);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Scegli");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Messaggio m = (Messaggio)jList1.getSelectedValue();
        this.syncBuffer.put(m);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaMessaggiCifrati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaMessaggiCifrati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaMessaggiCifrati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaMessaggiCifrati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
                
        final SynchronizedBuffer b = new SynchronizedBuffer();

        new Thread( new Runnable() {
            public void run() {
                ListaMessaggiCifrati listaMessaggiCifrati = new ListaMessaggiCifrati(b);
                listaMessaggiCifrati.setVisible(true);
            }
        } ).start();
        
        
        System.out.println( b.get() );
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
