/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI.spia;

import GUI.GenericSelector;
import java.util.List;
import java.util.Observable;
import model.spia.Ipotesi;
import model.spia.Sessione;
import model.spia.SostituzioneSemplice;

/**
 *
 * @author davide
 */
public class SostituzioneSempliceGUI extends javax.swing.JFrame {
  
    public static char[] getCaratteriDaSostituire() {
      
      final SynchronizedBuffer<char[]> buff = new SynchronizedBuffer<>();

      new Thread(new Runnable() {
        @Override
        public void run() {
          SostituzioneSempliceGUI frame = new SostituzioneSempliceGUI(buff);
          frame.setVisible(true);
        }
      }).start();

      return buff.get();
    }
    
    //<editor-fold desc="SynchronizedBuffer">
    private static class SynchronizedBuffer<T> {

    private T contents;
    private boolean available = false;

    public synchronized T get() {
      while (available == false) {
        try {
          wait();
        } catch (InterruptedException e) {
        }
      }
      available = false;
      notifyAll();
      return contents;
    }

    public synchronized void put(T value) {
      while (available == true) {
        try {
          wait();
        } catch (InterruptedException e) {
        }
      }
      contents = value;
      available = true;
      notifyAll();
    }
  }
  //</editor-fold>
    
    private SynchronizedBuffer<char[]> buff;
    /**
     * Creates new form SostituzioneLettera
     */
    private SostituzioneSempliceGUI() {
        initComponents();
    }
    
    private SostituzioneSempliceGUI( SynchronizedBuffer<char[]> buff ) {
    this();
    this.buff = buff;
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jTextField2 = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();

    jLabel1.setText("Sostituisci la lettera:");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel2.setText("Trasforma la lettera: ");

    jLabel3.setText("In:");

    jTextField1.setMaximumSize(new java.awt.Dimension(1, 1));
    jTextField1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField1ActionPerformed(evt);
      }
    });

    jButton1.setText("Sostituisci");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jLabel4.setText("Se inserisci più caratteri verrà preso in considerazione solo il primo");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jButton1)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
              .addGap(47, 47, 47)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel3)
                  .addGap(184, 184, 184)
                  .addComponent(jTextField2))
                .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel2)
                  .addGap(55, 55, 55)
                  .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
              .addContainerGap()
              .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(37, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(65, 65, 65)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel2)
          .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(39, 39, 39)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(18, 18, 18)
        .addComponent(jButton1)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        char[] array = new char[2];
        
        array[0] = jTextField1.getText().charAt(0);
        array[1] = jTextField2.getText().charAt(0);
                
        this.buff.put( array );
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

  private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextField1ActionPerformed


  public static void main( String[] args ) {
    char[] r = getCaratteriDaSostituire();
    System.out.println(r[0]+" "+r[1]);
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField2;
  // End of variables declaration//GEN-END:variables
}
